# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.CharField(default='Not Available', max_length=140),
            preserve_default=False,
        ),
    ]
